### ISSUE TITLE
atv

### ISSUE THREAD

**Issue by ws115** [yangqian/plugin.video.pandatv#1]

**Comment by ws115** [comment]
atv4上面kodi插件打不开
 WaitOnScriptResult - waiting on the áü?á?′TV(pandatv) (id=132) plugin...

e/Containers/Data/Application/77E9FEB2-A921-4B53-B350-759D5B2B9777/Library/Caches/home/addons/plugin.video.pandatv-master/addon.py", line 9, in <module>

```
    from BeautifulSoup import BeautifulSoup

ImportError: No module named BeautifulSoup

-->End of Python script error report<--
```

**Comment by yangqian** [comment]
I updated the module dependency, please check again. Should be working now.
